'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.42
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------


Imports Microsoft.VisualBasic
Imports System
Namespace HighlightFocused


	Partial Public Class _Default

		''' <summary>
		''' form1 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected form1 As Global.System.Web.UI.HtmlControls.HtmlForm

		''' <summary>
		''' ASPxLabel1 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected ASPxLabel1 As Global.DevExpress.Web.ASPxEditors.ASPxLabel

		''' <summary>
		''' ASPxTextBox1 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected ASPxTextBox1 As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

		''' <summary>
		''' ASPxLabel2 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected ASPxLabel2 As Global.DevExpress.Web.ASPxEditors.ASPxLabel

		''' <summary>
		''' ASPxDateEdit1 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected ASPxDateEdit1 As Global.DevExpress.Web.ASPxEditors.ASPxDateEdit

		''' <summary>
		''' ASPxLabel3 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected ASPxLabel3 As Global.DevExpress.Web.ASPxEditors.ASPxLabel

		''' <summary>
		''' ASPxMemo1 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected ASPxMemo1 As Global.DevExpress.Web.ASPxEditors.ASPxMemo
	End Class
End Namespace
